/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;


import Business.Enterprise.Enterprise;
import Business.Organization.HelpDeskOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Mugdha
 */
public class ViewHelpDeskInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewHelpDeskInfoJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    public ViewHelpDeskInfoJPanel(JPanel upc, Enterprise e) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = e;
        
        populateHelpTable();
        txtBestCustomer.setText(getBestEmployee());
        getBusyEmployee();
                
    }

    public void populateHelpTable(){
        
        try {
             tblHelpDesk.removeAll();
        DefaultTableModel model = (DefaultTableModel) tblHelpDesk.getModel();
        model.setRowCount(0);
        Organization org = null;
        
        for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
          if(o instanceof HelpDeskOrganization){
              org = o;
              break;
          }
        }
        
        for(UserAccount e : org.getUserAccountDirectory().getUserAccountList()){
            Object[] row = new Object[4];
            row[0] = e.getEmployee().getName();
            row[1] = e.getWorkQueue().getWorkRequestList().size();
            row[2] = e.getNumberOfResolvedIssues();
            row[3] = e.getNumberOfUnResolvedIssues();
            model.addRow(row);
         }
            
        } catch (Exception e) {
        }
       
     }
    
    private void getBusyEmployee() {
        Organization org = null;
        int count = 0;
        try {
            for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (o instanceof HelpDeskOrganization) {
                    org = o;
                    break;
                }
            }

            for(UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {

                if (ua.getEmployee().getStatus().equalsIgnoreCase("Busy")) {
                    count++;
                }
            }

            txtBusyEmployee.setText(String.valueOf(count));
            int size = org.getEmployeeDirectory().getEmployeeList().size();
            txtFreeEmployee.setText(String.valueOf(size - count));

           

        } catch (Exception e) {

        }
    }
     private String getBestEmployee() {
         
              float largest = Integer.MIN_VALUE;
        String name = "";
         Organization org = null;
        
        for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
          if(o instanceof HelpDeskOrganization){
              org = o;
              break;
          }
        }
        try{
        for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
            int size = ua.getWorkQueue().getWorkRequestList().size();
            int solved = ua.getNumberOfResolvedIssues();
            
            int fraction = (solved/size)*10;
                if ( fraction> largest) {
                    largest = fraction;
                    name = ua.getEmployee().getName();
                }            
        }
        }catch(Exception e){
        }
         return name;     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHelpDesk = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBestCustomer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBusyEmployee = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFreeEmployee = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnAnalysis = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblHelpDesk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblHelpDesk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HelpDesk Employee", "No of Quesries", "Resolved Quesries", "Unsolved Quesries"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHelpDesk);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Best HelpDesk Employee");

        txtBestCustomer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtBestCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBestCustomerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Busy HelpDesk Employee");

        txtBusyEmployee.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtBusyEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusyEmployeeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Free HelpDesk Employee");

        txtFreeEmployee.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtFreeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFreeEmployeeActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mugdha\\Documents\\NetBeansProjects\\Final Project\\src\\UserInterface\\Back.png")); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAnalysis.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAnalysis.setText("Analysis");
        btnAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(261, 261, 261)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFreeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtBusyEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBestCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBestCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBusyEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFreeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(btnAnalysis)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBestCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBestCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBestCustomerActionPerformed

    private void txtBusyEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusyEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusyEmployeeActionPerformed

    private void txtFreeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFreeEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFreeEmployeeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAnalyticsJPanel uwajp = (ManageAnalyticsJPanel) component;

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisActionPerformed
        // TODO add your handling code here:
        try {
            DefaultCategoryDataset dataset =  new DefaultCategoryDataset();
         Organization org = null;
        
        for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
          if(o instanceof HelpDeskOrganization){
              org = o;
              break;
          }
        }

        for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {

            dataset.setValue(ua.getNumberOfResolvedIssues(), "Resolved Issues", ua.getEmployee().getName());
        }
        JFreeChart chart = ChartFactory.createBarChart("No of resolved issues", "Employee name", "No of resolved issues", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLUE);
        ChartFrame frame = new ChartFrame("Bar Chart", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);

        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnAnalysisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHelpDesk;
    private javax.swing.JTextField txtBestCustomer;
    private javax.swing.JTextField txtBusyEmployee;
    private javax.swing.JTextField txtFreeEmployee;
    // End of variables declaration//GEN-END:variables
}
