/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import Business.Validations.MyBlankSpaceVerifier;
import Business.Validations.MyNameVerifier;
import Business.Validations.MyStringVerifier;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mugdha
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;

    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        MyNameVerifier myNameVerifier = new MyNameVerifier();
        txtName.setInputVerifier(myNameVerifier);

        MyStringVerifier myStringVerifier = new MyStringVerifier();
        txtUsername.setInputVerifier(myStringVerifier);

        MyBlankSpaceVerifier myBlankSpaceVerifier = new MyBlankSpaceVerifier();
        txtPassword.setInputVerifier(myBlankSpaceVerifier);

        populateTable();
        populateNetworkComboBox();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = userAccount.getUsername();

                    model.addRow(row);
                }
            }
        }
    }

    private void populateNetworkComboBox() {
        comboNetwork.removeAllItems();

        for (Network network : system.getNetworkList()) {
            comboNetwork.addItem(network);
        }
    }

    private void populateEnterpriseComboBox(Network network) {
        comboEnterprise.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            comboEnterprise.addItem(enterprise);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblNetwork = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        comboNetwork = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        lblEnterprise = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        comboEnterprise = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setEnabled(false);

        lblNetwork.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNetwork.setText("              Network");
        jDesktopPane1.add(lblNetwork);
        lblNetwork.setBounds(323, 193, 129, 32);

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnAdd);
        btnAdd.setBounds(259, 408, 415, 38);

        comboNetwork.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNetworkActionPerformed(evt);
            }
        });
        jDesktopPane1.add(comboNetwork);
        comboNetwork.setBounds(488, 194, 186, 30);

        tblEnterprise.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnterprise);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(257, 50, 417, 125);

        lblEnterprise.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEnterprise.setText("Enterprise Name");
        jDesktopPane1.add(lblEnterprise);
        lblEnterprise.setBounds(334, 238, 94, 17);

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jDesktopPane1.add(txtName);
        txtName.setBounds(488, 358, 186, 30);

        lblName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblName.setText("                       Name");
        jDesktopPane1.add(lblName);
        lblName.setBounds(299, 355, 129, 35);

        txtUsername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jDesktopPane1.add(txtUsername);
        txtUsername.setBounds(488, 270, 186, 32);

        lblUserName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblUserName.setText("                  Username");
        jDesktopPane1.add(lblUserName);
        lblUserName.setBounds(299, 269, 129, 32);

        lblPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPassword.setText("                  Password");
        jDesktopPane1.add(lblPassword);
        lblPassword.setBounds(299, 308, 129, 36);

        txtPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jDesktopPane1.add(txtPassword);
        txtPassword.setBounds(488, 312, 186, 29);

        comboEnterprise.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jDesktopPane1.add(comboEnterprise);
        comboEnterprise.setBounds(488, 231, 186, 30);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mugdha\\Desktop\\Back.png")); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        try {
            Enterprise enterprise = (Enterprise) comboEnterprise.getSelectedItem();
        int count = 0;
        String username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getText());
        String name = txtName.getText();
        

        
        if(txtName.getText().isEmpty() || txtUsername.getText().isEmpty() || txtPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Fields can't be empty!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else {
            try {
                for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    if (ua.getUsername().equalsIgnoreCase(username)) {
                        count++;
                    }
                }

                if (count == 0) {
                    Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);
                    enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new AdminRole());
                    populateTable();

                    
                } else {
                    JOptionPane.showMessageDialog(null, "This username already exists!", "Error", JOptionPane.ERROR_MESSAGE);

                }
            } catch (Exception e) {

            }
        } 
        } catch (Exception e) {
            
        }
        
       
    }//GEN-LAST:event_btnAddActionPerformed

    private void comboNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNetworkActionPerformed
        // TODO add your handling code here:
        Network network = (Network) comboNetwork.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }

    }//GEN-LAST:event_comboNetworkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboEnterprise;
    private javax.swing.JComboBox comboNetwork;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
