/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mugdha
 */
public class ManageAnalyticsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAnalyticsJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    public ManageAnalyticsJPanel( JPanel upc, Enterprise e) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnManageAnalytics = new javax.swing.JButton();
        btnManageAnalytics2 = new javax.swing.JButton();
        btnManageAnalytics1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setEnabled(false);

        btnManageAnalytics.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnManageAnalytics.setText("Manage TravelCard Details");
        btnManageAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAnalyticsActionPerformed(evt);
            }
        });

        btnManageAnalytics2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnManageAnalytics2.setText("Manage Snow Plow Details");
        btnManageAnalytics2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAnalytics2ActionPerformed(evt);
            }
        });

        btnManageAnalytics1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnManageAnalytics1.setText("Manage HelpDesk Details");
        btnManageAnalytics1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAnalytics1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mugdha\\Documents\\NetBeansProjects\\Final Project\\src\\UserInterface\\Back.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(btnManageAnalytics, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnManageAnalytics2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnManageAnalytics1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(458, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageAnalytics1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageAnalytics2))
                .addGap(416, 416, 416))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnManageAnalytics)
                .addGap(30, 30, 30)
                .addComponent(btnManageAnalytics1)
                .addGap(34, 34, 34)
                .addComponent(btnManageAnalytics2)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAnalyticsActionPerformed
        // TODO add your handling code here:
        ViewTravelCardDetailsJPanel manageAnalyticsJPanel = new ViewTravelCardDetailsJPanel(userProcessContainer, enterprise);
        
        userProcessContainer.add("manageAnalyticsJPanel", manageAnalyticsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAnalyticsActionPerformed

    private void btnManageAnalytics1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAnalytics1ActionPerformed
        // TODO add your handling code here:
        ViewHelpDeskInfoJPanel vhdijp = new ViewHelpDeskInfoJPanel(userProcessContainer, enterprise);
        
        userProcessContainer.add("view", vhdijp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAnalytics1ActionPerformed

    private void btnManageAnalytics2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAnalytics2ActionPerformed
        // TODO add your handling code here:
        ViewSnowPlowInfoJPanel vhdijp = new ViewSnowPlowInfoJPanel(userProcessContainer, enterprise);
        
        userProcessContainer.add("view", vhdijp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageAnalytics2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAnalytics;
    private javax.swing.JButton btnManageAnalytics1;
    private javax.swing.JButton btnManageAnalytics2;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
