/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SnowPlowRole;

import Business.Enterprise.Enterprise;
import Business.Organization.SnowPlowOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mugdha
 */
public class SnowPlowWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SnowPlowWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SnowPlowOrganization organization;
    private Enterprise enterprise;
    
    public SnowPlowWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SnowPlowOrganization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer= userProcessContainer;
        this.userAccount =account;
        this.organization = organization;
        this.enterprise = enterprise;
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnReportCleaning = new javax.swing.JButton();
        btnManageStreet = new javax.swing.JButton();
        btnSensorInfo = new javax.swing.JButton();
        btnGetSensorMeasur = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setEnabled(false);

        btnReportCleaning.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReportCleaning.setText("Report Cleaning");
        btnReportCleaning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportCleaningActionPerformed(evt);
            }
        });

        btnManageStreet.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnManageStreet.setText("Manage Street Information");
        btnManageStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStreetActionPerformed(evt);
            }
        });

        btnSensorInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSensorInfo.setText("Get Sensor Information");
        btnSensorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSensorInfoActionPerformed(evt);
            }
        });

        btnGetSensorMeasur.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnGetSensorMeasur.setText("Get Sensor Measurements");
        btnGetSensorMeasur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetSensorMeasurActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(btnReportCleaning, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnManageStreet, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnSensorInfo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnGetSensorMeasur, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReportCleaning, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetSensorMeasur, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSensorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStreet))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnManageStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSensorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnGetSensorMeasur, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnReportCleaning, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStreetActionPerformed
        // TODO add your handling code here:
        ManageStreetInfoJPanel msijp = new ManageStreetInfoJPanel(userProcessContainer, userAccount,organization,enterprise);
        userProcessContainer.add("manageStreetInformationJPanel", msijp);
       
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageStreetActionPerformed

    private void btnSensorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSensorInfoActionPerformed
        // TODO add your handling code here:
        GetSensorInfoJPanel gsijp = new GetSensorInfoJPanel(userProcessContainer, userAccount,organization,enterprise);
        userProcessContainer.add("GetSensorInfoJPanel", gsijp);
       
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSensorInfoActionPerformed

    private void btnGetSensorMeasurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetSensorMeasurActionPerformed
        // TODO add your handling code here:
        GetSensorMeasurementsJPanel rcjp = new GetSensorMeasurementsJPanel(userProcessContainer, userAccount,organization,enterprise);
        userProcessContainer.add("GetSensorInfoJPanel", rcjp);
       
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnGetSensorMeasurActionPerformed

    private void btnReportCleaningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportCleaningActionPerformed
        // TODO add your handling code here:
        ReportCleaningJPanel rcjp = new ReportCleaningJPanel(userProcessContainer, userAccount,organization,enterprise);
        userProcessContainer.add("GetSensorInfoJPanel", rcjp);
       
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReportCleaningActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetSensorMeasur;
    private javax.swing.JButton btnManageStreet;
    private javax.swing.JButton btnReportCleaning;
    private javax.swing.JButton btnSensorInfo;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
